- name: printing the variable
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print variable
    ansible.builtin.debug:
      msg: "Hii..Im learning {{COURSE}} and duration is {{Duration}}"
