- name: print the variable
  hosts: web
  vars:
    COURSE: devops with AWS
    Duration: 120hrs
  tasks:
  - name: printing the varialbles
    ansible.builtin.debug:
      msg: "Hi, im learning {{COURSE}}, duration is {{Duration}}"

  - name: printing variable again
    ansible.builtin.debug:
      msg: "Hi, im learning {{COURSE}}"