- name: To check number is less than or not
  hosts: local
  connection: local
  vars_prompt:
    - name: number
      prompt: please enter the number
      private: false
  tasks:
  - name: print if number less than 20
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than or not"
    when: number | int < 20
  
  - name: print if number greater than equal to 20
    ansible.builtin.debug:
      msg: "Given number {{number}} is greater than or equal to 20"
    when: number | int >= 20
  