- name: install package
  hosts: web
  become: yes
  tasks:
  - name: install package by using loops
    ansible.builtin.package:
     name: "{{ name.item }}"
     state: "{{ state.item }}"
    
    loop:
    - { name: 'mysql', state: 'absent' }
    - { name: 'nginx', state: 'present' }