- name: print the variables
  hosts: web
  vars_prompt:
    - name: COURSE
      prompt: please enter the course name

    - name: Duration
      prompt: please enter the course duration
  
  tasks:
    - name: printing the variable again
      ansible.builtin.debug:
        msg: "Hii. I am learning {{COURSE}} and duration is {{Duration}}"
