- name: install package
  hosts: web
  become: yes
  tasks:
  - name: install package by using loops
    ansible.builtin.package:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    
    loop:
    - { name: 'mysql', state: 'absent' }
    - { name: 'nginx', state: 'present' }